import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SplashWrapper from "@/providers/SplashWrapper";
import UIProvider from "@/providers/UIProvider";

const InterSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${InterSans.className} bg-background text-foreground min-h-screen
          antialiased`}
      >
        <SplashWrapper>
          <UIProvider />
          {children}
        </SplashWrapper>
      </body>
    </html>
  );
}
