import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import SplashWrapper from "@/providers/SplashWrapper";
import UIProvider from "@/providers/UIProvider";
import ReactQueryClientProvider from "@/providers/ReactQueryProvider";

const InterSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${InterSans.className} bg-slate-100 text-foreground min-h-screen
          antialiased`}
      >
        <ReactQueryClientProvider>
          <SplashWrapper>
            <UIProvider />
            {children}
          </SplashWrapper>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
