import image from "@/assets/images/avatar.jpeg";

export const salaryDueListData = [
  {
    _id: "1",
    employeeId: {
      _id: "1",
      fullName: "John Doe",
      avatar: image,
      designation: "Software Engineer",
    },
    baseSalary: 50000,
    allowance: 5000,
    month: "January",
    status: "due",
  },
  {
    _id: "2",
    employeeId: {
      _id: "2",
      fullName: "Sarah Ahmed",
      avatar: image,
      designation: "UI/UX Designer",
    },
    baseSalary: 45000,
    allowance: 4000,
    month: "January",
    status: "due",
  },
  {
    _id: "3",
    employeeId: {
      _id: "3",
      fullName: "Michael Smith",
      avatar: image,
      designation: "Frontend Developer",
    },
    baseSalary: 48000,
    allowance: 3000,
    month: "February",
    status: "due",
  },
  {
    _id: "4",
    employeeId: {
      _id: "4",
      fullName: "Ayesha Rahman",
      avatar: image,
      designation: "HR Executive",
    },
    baseSalary: 40000,
    allowance: 2000,
    month: "February",
    status: "due",
  },
  {
    _id: "5",
    employeeId: {
      _id: "5",
      fullName: "David Lee",
      avatar: image,
      designation: "Backend Developer",
    },
    baseSalary: 52000,
    allowance: 4500,
    month: "March",
    status: "due",
  },
  {
    _id: "6",
    employeeId: {
      _id: "6",
      fullName: "Nusrat Jahan",
      avatar: image,
      designation: "Marketing Manager",
    },
    baseSalary: 47000,
    allowance: 3500,
    month: "March",
    status: "due",
  },
  {
    _id: "7",
    employeeId: {
      _id: "7",
      fullName: "James Brown",
      avatar: image,
      designation: "Accountant",
    },
    baseSalary: 43000,
    allowance: 2500,
    month: "April",
    status: "due",
  },
  {
    _id: "8",
    employeeId: {
      _id: "8",
      fullName: "Emily Carter",
      avatar: image,
      designation: "Project Manager",
    },
    baseSalary: 60000,
    allowance: 6000,
    month: "April",
    status: "due",
  },
  {
    _id: "9",
    employeeId: {
      _id: "9",
      fullName: "Rafiul Hasan",
      avatar: image,
      designation: "Support Engineer",
    },
    baseSalary: 38000,
    allowance: 2000,
    month: "May",
    status: "due",
  },
  {
    _id: "10",
    employeeId: {
      _id: "10",
      fullName: "Olivia Johnson",
      avatar: image,
      designation: "QA Analyst",
    },
    baseSalary: 42000,
    allowance: 2500,
    month: "May",
    status: "due",
  },
  {
    _id: "11",
    employeeId: {
      _id: "11",
      fullName: "Imran Hossain",
      avatar: image,
      designation: "Network Engineer",
    },
    baseSalary: 46000,
    allowance: 3000,
    month: "June",
    status: "due",
  },
  {
    _id: "12",
    employeeId: {
      _id: "12",
      fullName: "Sophia Wilson",
      avatar: image,
      designation: "Content Writer",
    },
    baseSalary: 35000,
    allowance: 1500,
    month: "June",
    status: "due",
  },
  {
    _id: "13",
    employeeId: {
      _id: "13",
      fullName: "Rajesh Kumar",
      avatar: image,
      designation: "DevOps Engineer",
    },
    baseSalary: 55000,
    allowance: 5000,
    month: "July",
    status: "due",
  },
  {
    _id: "14",
    employeeId: {
      _id: "14",
      fullName: "Emma Thomas",
      avatar: image,
      designation: "Graphic Designer",
    },
    baseSalary: 39000,
    allowance: 2500,
    month: "July",
    status: "due",
  },
  {
    _id: "15",
    employeeId: {
      _id: "15",
      fullName: "Hasan Ali",
      avatar: image,
      designation: "Technical Lead",
    },
    baseSalary: 65000,
    allowance: 7000,
    month: "August",
    status: "due",
  },
  {
    _id: "16",
    employeeId: {
      _id: "16",
      fullName: "Liam Anderson",
      avatar: image,
      designation: "Business Analyst",
    },
    baseSalary: 52000,
    allowance: 4000,
    month: "August",
    status: "due",
  },
  {
    _id: "17",
    employeeId: {
      _id: "17",
      fullName: "Sadia Islam",
      avatar: image,
      designation: "HR Manager",
    },
    baseSalary: 49000,
    allowance: 3000,
    month: "September",
    status: "due",
  },
  {
    _id: "18",
    employeeId: {
      _id: "18",
      fullName: "Noah Patel",
      avatar: image,
      designation: "Full Stack Developer",
    },
    baseSalary: 57000,
    allowance: 4500,
    month: "September",
    status: "due",
  },
  {
    _id: "19",
    employeeId: {
      _id: "19",
      fullName: "Maya Ahmed",
      avatar: image,
      designation: "Finance Officer",
    },
    baseSalary: 44000,
    allowance: 2500,
    month: "October",
    status: "due",
  },
  {
    _id: "20",
    employeeId: {
      _id: "20",
      fullName: "Ethan Scott",
      avatar: image,
      designation: "Sales Executive",
    },
    baseSalary: 39000,
    allowance: 2000,
    month: "October",
    status: "due",
  },
];
